#!/usr/bin/env python3

import os
import sys
import time
import datetime
import serial
import argparse
import requests
import json
import struct
from struct import unpack

parser = argparse.ArgumentParser(description='EPOS Serial->IoT Gateway')

required = parser.add_argument_group('required named arguments')
required.add_argument('-c','--certificate', help='Your PEM certificate', required=True)

parser.add_argument('-d','--dev', help='EPOSMote III device descriptor file', default='/dev/ttyACM0')
parser.add_argument('-t','--timeout', help='Timeout for reading from mote', default=600)
parser.add_argument('-gu','--get_url', help='GET URL', default='https://iot.lisha.ufsc.br/api/get.php')
parser.add_argument('-u','--url', help='Post URL', default='https://iot.lisha.ufsc.br/api/put.php')
parser.add_argument('-a','--attach_url', help='Attach URL', default='https://iot.lisha.ufsc.br/api/attach.php')
# parser.add_argument('-j','--json', help='Use JSON API', action='store_true')
parser.add_argument('-D','--domain', help='Data domain', default='smartpark')
parser.add_argument('-U','--username', help='Data domain username', default='smartpark')
parser.add_argument('-P','--password', help='User password', default='')

args = vars(parser.parse_args())
DEV = args['dev']
TIMEOUT = int(args['timeout'])
URL = args['url']
ATTACH_URL = args['attach_url']
GET_URL = args['get_url']
MY_CERTIFICATE = args['certificate']
DOMAIN = args['domain']
USERNAME = args['username']
PASSWORD = args['password']

def unix_time_millis(dt):
    return str(int(dt * 1000000))

if __name__ == "__main__":
    session = requests.Session()
    session.headers = {'Content-type' : 'application/json'}

    session.cert = MY_CERTIFICATE

    print("Lendo dados da núvem")
    t0 = unix_time_millis(time.mktime(datetime.datetime.strptime("01/06/2017", "%d/%m/%Y").timetuple()));
    t1 = unix_time_millis(time.mktime(datetime.datetime.strptime("31/12/2017", "%d/%m/%Y").timetuple()));
    request_data = {
        'series' :
        {
            'version' : "1.1",
            'unit' : 2224441636,
            'x' : 10,
            'y' : 10,
            'z' : 0,
            'r' : 1000,
            't0': t0,
            't1': t1,
        },
        'credentials': {
            'domain' : DOMAIN,
            'username' : USERNAME,
            'password' : PASSWORD
        }
    }
    print(json.dumps(request_data))
    response = session.post(GET_URL, json.dumps(request_data))
    print("POST [", str(response.status_code), "]")
    print(response.text)
