#!/usr/bin/env python3

import os
import sys
import time
import serial
import argparse
import requests
import datetime

parser = argparse.ArgumentParser(description='EPOS Serial->IoT Gateway')

required = parser.add_argument_group('required named arguments')
required.add_argument('-c','--certificate', help='Your PEM certificate', required=True)

parser.add_argument('-d','--dev', help='EPOSMote III device descriptor file', default='/dev/ttyACM0')
parser.add_argument('-t','--timeout', help='Timeout for reading from mote', default=600)
parser.add_argument('-gu','--get_url', help='GET URL', default='https://iot.lisha.ufsc.br/api/get.php')
parser.add_argument('-u','--url', help='Post URL', default='https://iot.lisha.ufsc.br/api/put.php')
parser.add_argument('-a','--attach_url', help='Attach URL', default='https://iot.lisha.ufsc.br/api/attach.php')
# parser.add_argument('-j','--json', help='Use JSON API', action='store_true')
parser.add_argument('-D','--domain', help='Data domain', default='smartpark')
parser.add_argument('-U','--username', help='Data domain username', default='smartpark')
parser.add_argument('-P','--password', help='User password', default='')

args = vars(parser.parse_args())
DEV = args['dev']
TIMEOUT = int(args['timeout'])
URL = args['url']
ATTACH_URL = args['attach_url']
GET_URL = args['get_url']
MY_CERTIFICATE = args['certificate']
DOMAIN = args['domain']
USERNAME = args['username']
PASSWORD = args['password']
JSON = True

# TIMESTAMP = 1509470765582000
TIMESTAMP = int(datetime.datetime.now().timestamp()*1000000)

if JSON:
    import json
    import struct
    from struct import unpack

def to_json():
    value = 20
    error = 0
    confidence = 1
    x = 6
    y = 7
    z = 8
    t = TIMESTAMP

    version = "1.1" # Version 1, Static
    unit = 2224441636
    center_x = x
    center_y = y
    center_z = z
    r = 10
    t0 = TIMESTAMP-1
    t1 = TIMESTAMP+1

    if DOMAIN or USERNAME or PASSWORD:
        credentials = {}
        if DOMAIN:
            credentials['domain'] = DOMAIN
        if USERNAME:
            credentials['username'] = USERNAME
        if PASSWORD:
            credentials['password'] = PASSWORD

    data_ret_obj = {
            'smartdata' :
            [
                {
                    'version' : version,
                    'unit' : unit,
                    'error' : error,
                    'confidence' : confidence,
                    'x' : x,
                    'y' : y,
                    'z' : z,
                    'value' : value,
                    'time' : t,
                    'mac' : 0
                }
            ]
        }

    if DOMAIN or USERNAME or PASSWORD:
        data_ret_obj['credentials'] = credentials

    series_ret_obj = {
            'series' :
            {
                'version' : version,
                'unit' : unit,
                'x' : center_x,
                'y' : center_y,
                'z' : center_z,
                'r' : r,
                't0' : t0,
                't1' : t1
            }
        }

    if DOMAIN or USERNAME or PASSWORD:
        series_ret_obj['credentials'] = credentials

    data_ret = json.dumps(data_ret_obj)
    series_ret = json.dumps(series_ret_obj)

    return series_ret, data_ret

attached = []

if __name__ == "__main__":
    session = requests.Session()
    session.headers = {'Content-type' : 'application/json'}

    session.cert = MY_CERTIFICATE

    print("Enviando dados JSON para a núvem", file=sys.stderr)
    [series, smartdata] = to_json()
    if not series in attached:
        response = session.post(ATTACH_URL, series)
        print("POST [", str(response.status_code), "] (", len(series), ") ", series, sep='')
        attached.append(series)

    response = session.post(URL, smartdata)
    print("POST [", str(response.status_code), "] (", len(smartdata), ") ", smartdata, sep='')

    print("Lendo dados da núvem")
    t0 = TIMESTAMP-1
    t1 = TIMESTAMP+1
    request_data = {
        'series' :
        {
            'version' : "1.1",
            'unit' : 2224441636,
            'x' : 6,
            'y' : 7,
            'z' : 8,
            'r' : 10,
            't0': t0,
            't1': t1,
        },
        'credentials': {
            'domain' : DOMAIN,
            'username' : USERNAME,
            'password' : PASSWORD
        }
    }
    response = session.post(GET_URL, json.dumps(request_data))
    print("POST [", str(response.status_code), "]")
    print(response.text)
